### ISSUE TITLE
Custom destination?

### ISSUE THREAD

**Issue by norrstv** [PercyFN/Compass-Device#1]
Hi! I managed to set the compass and the enable and disable button but it takes me to 400 meters into a random direction, how do I make it so it gets me to a custom destination? 

I want it to get to a radio and place the disable button there being the same one as the pickup the radio one 

![image](https://github.com/user-attachments/assets/ca3c6d09-9c5d-4098-b822-592815cffe40)

I'm guessing to put the target location has to do something with this but im so bad at verse code so please help♥ 
![image](https://github.com/user-attachments/assets/b6b54174-ea08-4592-8aee-ed070db531f9)

**Comment by PercyFN** [comment]
You can edit this line of code and replace "GetRandomLocation()" with for example "vector3{X:=0.0,Y:=0.0,Z:=0.0}":

        # Get a random target location
        TargetLocation : vector3 = GetRandomLocation()
